local bonusOnHit = {
	LLWEAPONEX_BULLETS_AIR = "Electrify;SHOCKED,10,1",
	LLWEAPONEX_BULLETS_BLOOD = "BLEEDING,10,1",
	LLWEAPONEX_BULLETS_EARTH = "SLOWED,10,1",
	LLWEAPONEX_BULLETS_FIRE = "Ignite;Melt;BURNING,10,1",
	LLWEAPONEX_BULLETS_ICE = "Freeze;CHILLED,10,1",
	LLWEAPONEX_BULLETS_POISON = "Contaminate;POISONED,10,1",
	LLWEAPONEX_BULLETS_WATER = "Douse;WET,30,1",
}