Ext.Require("Shared/Mastery/Data/Masteries.lua")
Ext.Require("Shared/Mastery/MasteryEvents.lua")
Ext.Require("Shared/Mastery/MasteryRankBonusManager.lua")
Ext.Require("Shared/Mastery/MasteryHelpers.lua")
Ext.Require("Shared/Mastery/MasteryRegistration.lua")