Ext.Require("Shared/Mastery/Classes/MasteryData.lua")
Ext.Require("Shared/Mastery/Classes/MasteryRankBonus.lua")
Ext.Require("Shared/Mastery/Data/Masteries.lua")
Ext.Require("Shared/Mastery/Data/ElementalWeakness.lua")
Ext.Require("Shared/Mastery/MasteryRankBonusManager.lua")
Ext.Require("Shared/Mastery/MasteryHelpers.lua")
Ext.Require("Shared/Mastery/MasteryRegistration.lua")